# Largest prime factor of 600851475143
# NORMAL (<1s)
# 
# APPROACH: 
#   - The largest prime factor of the nuber above is below sqrt of itself.
#   - The primes are generated by a sieve.

from .helpers import primes_until
from math import floor

DUMMY_TARGET = 13195
DUMMY_RESULT = 29

TARGET = 600851475143

def max_factor(n):
    primes = reversed(list(primes_until(floor(n**.5))))

    for prime in primes:
        if not n % prime:
            return prime

assert max_factor(DUMMY_TARGET) == DUMMY_RESULT
result = max_factor(TARGET)